# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-mhcquant-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::r-rmarkdown=2.1
  - openms=2.5.0
  - comet-ms=2016013
  - python=2.7.15
  - mhcflurry=1.4.3
  - fred2=2.0.6
  - mhcnuggets=2.3.2 